### ISSUE TITLE
bug: dark theme does not change the color of the progress bar for the current song playing (if you are the active DJ)

### ISSUE THREAD

**Issue by mattbardal** [keithradford/ttfm-plus#10]
#### Bug
The progress bar on the song you are currently playing is a light blue color that clashes with the dark mode theme. 

#### Possible Solution
Find the class/id of the progress bar and re-apply a different color to it so the light blue background does not clash with the white text.

**Comment by PlusJack** [comment]
Image of the progress bar in dark mode: 

![image](https://user-images.githubusercontent.com/6070672/129970510-8147be32-4c75-4dcd-810e-8eeddbae1936.png)

**Comment by PlusJack** [comment]
Line separators should also be a less jarring color than white, like a dark grey. Chat settings icon should also be styled differently.

![image](https://user-images.githubusercontent.com/6070672/129970676-0e8251fa-3929-4089-9de5-f87eae06f551.png)

**Comment by PlusJack** [comment]
Room info tab text is too dark

![image](https://user-images.githubusercontent.com/6070672/129970918-dc349788-b98f-4f46-a728-d6f6602f90f2.png)
